[toolchain]
channel = "nightly"
components = ["rust-src"]
profile = "minimal"
targets = [
    "x86_64-unknown-none",
    "aarch64-unknown-none-softfloat",
    "riscv64imac-unknown-none-elf",
    "loongarch64-unknown-none-softfloat"
]
