[unstable]
build-std = ["core", "alloc"]
build-std-features = ["optimize_for_size"]
json-target-spec = true

[build]
rustflags = [
  "-Zlocation-detail=none",
  "-Zfmt-debug=none",
  "-Zunstable-options",
  "-Cpanic=immediate-abort",
]
target = [
  "x86_64-unknown-none",
  "i686-unknown-none.json",
  "aarch64-unknown-none-softfloat",
  "riscv64imac-unknown-none-elf",
  "loongarch64-unknown-none-softfloat"
]
